### ISSUE TITLE
Cannot find symbol 'sun.misc.Cleaner' on MacOS/Java 9

### ISSUE THREAD

**Issue by bendyarm** [bitcoinj/bitcoinj#1477]
I followed the instructions for a full build but I got a compilation error.
MacOS 10.13.1
Java version: 9.0.1
Apache Maven 3.5.2
git clone ...bitcoinj
mvn clean package

Here's the relevant output:
```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.2:compile (default-compile) on project bitcoinj-core: Compilation failure
[ERROR] [snipped]/bitcoinj/core/src/main/java/org/bitcoinj/store/WindowsMMapHack.java:[36,9] cannot find symbol
[ERROR]   symbol:   class Cleaner
[ERROR]   location: class org.bitcoinj.store.WindowsMMapHack
```

**Comment by schildbach** [comment]
What branch/tag/commit hash are you on?

**Comment by bendyarm** [comment]
master.

```
$ git status
On branch master
Your branch is up-to-date with 'origin/master'.
nothing to commit, working tree clean
$ git log | head -n 1
commit 9f5f973d8a41b3f97157939d38479d17b884ce21
$ 
```

**Comment by schildbach** [comment]
Can you try Java 8? Seems like the `sun.misc.Cleaner` class was removed.

**Comment by tompreston** [comment]
Hi,
I'm also getting stuck here. How do I tell maven to use Java 8? I've tried the sample here https://www.mkyong.com/maven/how-to-tell-maven-to-use-java-8/ 

like so:
```
diff --git a/pom.xml b/pom.xml
index 4a06e1eb..bd78d667 100644
--- a/pom.xml
+++ b/pom.xml
@@ -192,6 +192,8 @@
   <properties>
     <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
     <generated.sourceDirectory>gen</generated.sourceDirectory>
+    <maven.compiler.target>1.8</maven.compiler.target>
+    <maven.compiler.source>1.8</maven.compiler.source>
   </properties>

   <profiles>
```

but I'm still seeing the error:
```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.2:compile (default-compile) on project bitcoinj-core: Compilation failure
[ERROR] [also snip]/bitcoinj/core/src/main/java/org/bitcoinj/store/WindowsMMapHack.java:[34,9] cannot find symbol
[ERROR]   symbol:   class Cleaner
[ERROR]   location: class org.bitcoinj.store.WindowsMMapHack
```

I'm not familiar with maven/JDK.

Thanks

**Comment by dbkingsb** [comment]
Maven should be using $JAVA_HOME to choose which version of Java to use, however check to see if it is overwritten in ~/.mavenrc.

Here is an article about [maven & java home & osx](https://blog.tompawlak.org/maven-default-java-version-mac-osx)

**Comment by tompreston** [comment]
Thanks @dbkingsb, that article was really useful. I installed [JDK 8](http://www.oracle.com/technetwork/java/javase/downloads/jdk8-downloads-2133151.html) and changed my `~/.mavenrc`:

```
$ /usr/libexec/java_home -V
Matching Java Virtual Machines (2):
    9.0.1, x86_64:	"Java SE 9.0.1"	/Library/Java/JavaVirtualMachines/jdk-9.0.1.jdk/Contents/Home
    1.8.0_151, x86_64:	"Java SE 8"	/Library/Java/JavaVirtualMachines/jdk1.8.0_151.jdk/Contents/Home

/Library/Java/JavaVirtualMachines/jdk-9.0.1.jdk/Contents/Home

$ cat ~/.mavenrc
JAVA_HOME=`/usr/libexec/java_home -v 1.8.0_151`
```

wallet-tool builds now.

**Comment by uneeb123** [comment]
Is Java 9 not supported?

**Comment by schildbach** [comment]
FYI, there is a PR https://github.com/bitcoinj/bitcoinj/pull/1533 to migrate from Maven to Gradle.

I wonder if WindowsMMapHack.java can maybe simply be removed due to the underlying problem fixed in newer versions of Windows. If it needs to be kept, perhaps we should use reflection?

**Comment by shadders** [comment]
I've been investigating this issue for bitcoinj.cash and reflection is the
only satisfactory solution I can find but it does depend on whether the
problem still exists in newer windows. Do you have a reference that
indicates it is? I've exhausted all my Google-fu trying to answer that
question.

**Comment by schildbach** [comment]
I added two tests (dbc4c3520989ecd24b2f81c97cca8903ff15ee7f) that can hopefully aid to reproduce the original issue. Is there some volunteer running Windows?

**Comment by tofutim** [comment]
I have this issue on a Mac.
![image](https://user-images.githubusercontent.com/157766/38177269-a003599e-35b3-11e8-98c7-182f7f119bc8.png)
```
Matching Java Virtual Machines (3):
    1.8.0_161, x86_64:	"Java SE 8"	/Library/Java/JavaVirtualMachines/jdk1.8.0_161.jdk/Contents/Home
    1.8.0_121, x86_64:	"Java SE 8"	/Library/Java/JavaVirtualMachines/jdk1.8.0_121.jdk/Contents/Home
    1.7.0_71, x86_64:	"Java SE 7"	/Library/Java/JavaVirtualMachines/jdk1.7.0_71.jdk/Contents/Home
```

**Comment by schildbach** [comment]
Resolved via 1700ec0be4fe50a1b7ea95d6af0e46f876746333.

I removed the mmap hack for Windows. Let's see if some of the Windows folks complain.

**Comment by schildbach** [comment]
We should add the failing test to master.

**Comment by oscarguindzberg** [comment]
I added the test to https://github.com/bitcoinj/bitcoinj/pull/1695

**Comment by msgilligan** [comment]
@schildbach I think we can close this one.

**Comment by schildbach** [comment]
That's right. The test Oscar mentioned was merged.
