### ISSUE TITLE
java.lang.IllegalStateException: Ran out of space to store chain work!

### ISSUE THREAD

**Issue by snex** [bitcoinj/bitcoinj#3410]
This is happening when trying to add to SPV chain file (from https://github.com/bisq-network/bisq/)

Jun 23 08:44:26 bisq bisq-Bisq.desktop[263666]: #033[0;39m#033[31mJun-23 08:44:26.728 [NioClientManager] WARN  org.bitcoinj.core.PeerSocketHandler: [127.0.0.1]:8333 -  java.lang.IllegalStateException: Ran out of space to store chain work!
Jun 23 08:44:26 bisq bisq-Bisq.desktop[263666]: #011at com.google.common.base.Preconditions.checkState(Preconditions.java:510)
Jun 23 08:44:26 bisq bisq-Bisq.desktop[263666]: #011at org.bitcoinj.core.StoredBlock.serializeCompact(StoredBlock.java:121)
Jun 23 08:44:26 bisq bisq-Bisq.desktop[263666]: #011at org.bitcoinj.store.SPVBlockStore.put(SPVBlockStore.java:201)
Jun 23 08:44:26 bisq bisq-Bisq.desktop[263666]: #011at org.bitcoinj.core.BlockChain.addToBlockStore(BlockChain.java:93)
Jun 23 08:44:26 bisq bisq-Bisq.desktop[263666]: #011at org.bitcoinj.core.AbstractBlockChain.connectBlock(AbstractBlockChain.java:543)
Jun 23 08:44:26 bisq bisq-Bisq.desktop[263666]: #011at org.bitcoinj.core.AbstractBlockChain.add(AbstractBlockChain.java:469)
Jun 23 08:44:26 bisq bisq-Bisq.desktop[263666]: #011at org.bitcoinj.core.AbstractBlockChain.add(AbstractBlockChain.java:361)
Jun 23 08:44:26 bisq bisq-Bisq.desktop[263666]: #011at org.bitcoinj.core.BlockChain.add(BlockChain.java:170)
Jun 23 08:44:26 bisq bisq-Bisq.desktop[263666]: #011at org.bitcoinj.core.Peer.endFilteredBlock(Peer.java:1072)
Jun 23 08:44:26 bisq bisq-Bisq.desktop[263666]: #011at org.bitcoinj.core.Peer.processMessage(Peer.java:454)
Jun 23 08:44:26 bisq bisq-Bisq.desktop[263666]: #011at org.bitcoinj.core.PeerSocketHandler.receiveBytes(PeerSocketHandler.java:187)
Jun 23 08:44:26 bisq bisq-Bisq.desktop[263666]: #011at org.bitcoinj.net.ConnectionHandler.handleKey(ConnectionHandler.java:238)
Jun 23 08:44:26 bisq bisq-Bisq.desktop[263666]: #011at org.bitcoinj.net.NioClientManager.handleKey(NioClientManager.java:86)
Jun 23 08:44:26 bisq bisq-Bisq.desktop[263666]: #011at org.bitcoinj.net.NioClientManager.run(NioClientManager.java:122)
Jun 23 08:44:26 bisq bisq-Bisq.desktop[263666]: #011at com.google.common.util.concurrent.AbstractExecutionThreadService$1$2.run(AbstractExecutionThreadService.java:66)
Jun 23 08:44:26 bisq bisq-Bisq.desktop[263666]: #011at com.google.common.util.concurrent.Callables$4.run(Callables.java:117)
Jun 23 08:44:26 bisq bisq-Bisq.desktop[263666]: #011at org.bitcoinj.utils.ContextPropagatingThreadFactory$1.run(ContextPropagatingThreadFactory.java:51)
Jun 23 08:44:26 bisq bisq-Bisq.desktop[263666]: #011at java.base/java.lang.Thread.run(Thread.java:829)

**Comment by suddenwhipvapor** [comment]
Can confirm this looks like a common issue hitting Bisq users

**Comment by snex** [comment]
Seems to be happening when trying to add block 849,138

**Comment by msgilligan** [comment]
I'm looking in to the issue...

**Comment by msgilligan** [comment]
Re-opening this issue until 0.16.3 is released.

**Comment by schildbach** [comment]
0.16.3 is released now, so feel free to close.

https://github.com/bitcoinj/bitcoinj/releases/tag/v0.16.3

**Comment by udhishthirahakuntiputro** [comment]
I am experiencing related problem in my application using bitcoinj - can't sync past height 849137.  Started yesterday June 24 in all of my environments.  I have tried to redownload bitcoinj(0.16.2) maven dependency to get the fix today June 25.  It did not help.  Here is my app log (bitcoinj logging set to INFO):
java.nio.channels.CancelledKeyException: null
	at java.base/sun.nio.ch.SelectionKeyImpl.ensureValid(SelectionKeyImpl.java:75) ~[na:na]
	at java.base/sun.nio.ch.SelectionKeyImpl.readyOps(SelectionKeyImpl.java:138) ~[na:na]
	at java.base/java.nio.channels.SelectionKey.isWritable(SelectionKey.java:378) ~[na:na]
	at org.bitcoinj.net.ConnectionHandler.handleKey(ConnectionHandler.java:245) ~[bitcoinj-core-0.16.2.jar:na]
	at org.bitcoinj.net.NioClientManager.handleKey(NioClientManager.java:86) ~[bitcoinj-core-0.16.2.jar:na]
	at org.bitcoinj.net.NioClientManager.run(NioClientManager.java:122) ~[bitcoinj-core-0.16.2.jar:na]
	at com.google.common.util.concurrent.AbstractExecutionThreadService$1$2.run(AbstractExecutionThreadService.java:66) ~[guava-31.0.1-android.jar:na]
	at com.google.common.util.concurrent.Callables$4.run(Callables.java:121) ~[guava-31.0.1-android.jar:na]
	at org.bitcoinj.utils.ContextPropagatingThreadFactory$1.run(ContextPropagatingThreadFactory.java:50) ~[bitcoinj-core-0.16.2.jar:na]
	at java.base/java.lang.Thread.run(Thread.java:840) ~[na:na]

2024-06-25T09:22:46.361-04:00  INFO 50918 --- [eerGroup Thread] c.PeerGroup$ChainDownloadSpeedCalculator : 0 blocks/sec, 0 tx/sec, 0 pre-filtered tx/sec, avg/last 0.00/0.00 kilobytes per sec, chain/common height 849137/849440, stall disabled (threshold <0.78 KB/sec for 10 seconds).  

Please help!  This breaks my prod environment.

**Comment by msgilligan** [comment]
> 0.16.3 is released now, so feel free to close.
> 
> https://github.com/bitcoinj/bitcoinj/releases/tag/v0.16.3

I think we should wait on closing this, so that people coming to this repo will see it rather than create new issues.

**Comment by msgilligan** [comment]
>  can't sync past height 849137. Started yesterday June 24 in all of my environments. I have tried to redownload bitcoinj(0.16.2) maven dependency to get the fix today June 25.

0.16.2 did not change, it will still have the bug.
You need to upgrade to 0.16.3.

**Comment by msgilligan** [comment]
> > 0.16.3 is released now, so feel free to close.
> > https://github.com/bitcoinj/bitcoinj/releases/tag/v0.16.3
> 
> I think we should wait on closing this, so that people coming to this repo will see it rather than create new issues.

I changed my mind on this. I added a **bolded** note at the top of Issue #3415 to indicate that the short-term issue was fixed by this issue. Marking this issue as closed may actually help reduce confusion.

**Comment by Krokochik** [comment]
Why isn't it fixed on latest alpha versions like 0.**17** but on release 0.**16**.3?

**Comment by schildbach** [comment]
> Why isn't it fixed on latest alpha versions like 0.**17** but on release 0.**16**.3?

We didn't roll an updated alpha yet because it's not fully fixed. We only kicked the can down the road by utilizing the sign bit of the 12 bytes. We're working on extending those 12 bytes to 32.

Most of the work has been done on master – can you use that in the meantime?

**Comment by Krokochik** [comment]
> > Why isn't it fixed on latest alpha versions like 0.**17** but on release 0.**16**.3?
> 
> We didn't roll an updated alpha yet because it's not fully fixed. We only kicked the can down the road by utilizing the sign bit of the 12 bytes. We're working on extending those 12 bytes to 32.
> 
> Most of the work has been done on master – can you use that in the meantime? Or alternatively, just use testnet or signet.

Yeah, thanks. I currently applied this temporal fixes by overriding several bitcoinj classes and have a luck to keep using alpha thread

**Comment by schildbach** [comment]
Block 929024 has chain work 100439a41425c7aa5bcf5cfe3₁₆. It seems we recently flipped to requiring more than 96 bits.

**Comment by schildbach** [comment]
For the record: block 928896, mined on 2025-12-21 22:28:26 UTC, was the first block to require more than 96 bits.
